version: "3.8"

x-settings:
  &global
  environment:
    - CELERY_BROKER=${CELERY_BROKER}
    - RABBITMQ_USER=${RABBITMQ_USER}
    - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    restart: always

  celery_worker:
    build:
      context: .
      dockerfile: celery.Dockerfile
    container_name: worker
    <<: *global
    depends_on:
      - rabbitmq
    restart: always
    command: [ "worker" ]
    volumes:
      - .:/usr/src/app

  celery-beat:
    build:
      context: .
      dockerfile: celery.Dockerfile
    container_name: beat
    <<: *global
    depends_on:
      - rabbitmq
      - celery_worker
    command: [ "beat" ]
    volumes:
      - .:/usr/src/app
